source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml
src.includes = src/,\
               META-INF/,\
               plugin.xml,\
               build.properties
jre.compilation.profile = JavaSE-11

# Made with Bob
